name: Cron
on:
  push:
    branches: ['*']
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        include:
          - { version: 17 }
    name: PostgreSQL ${{ matrix.version }}
    runs-on: ubuntu-latest
    container: rodoq/postgres-extension
    env:
      PGUSER: postgres
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get install -y --no-install-recommends postgresql-${{ matrix.version }}-pgtap
      - run: psql -c 'CREATE DATABASE test'
      - run: psql -d test -c 'CREATE EXTENSION pgtap'
      - run: psql -d test -c 'CREATE EXTENSION dblink'
      - run: psql -d test -c 'CREATE EXTENSION postgres_fdw'
      # Basic regression test.
      - run: pg-build-test

      # Test all, install, test, test-serial, and test-parallel, both from clean
      # repo and repeated with existing build, with and without PARALLEL_CONN=1.
      - run: make uninstall clean
      - run: make all
      - run: make install
      - run: psql -d -c 'CREATE EXTENSION data_historization'
      - run: psql -d test "CREATE SERVER historize_foreign_cron FOREIGN DATA WRAPPER dblink_fdw OPTIONS (host 'localhost', port '5432', dbname 'postgres', options '-csearch_path=cron')"
      - run: psql -d -c "CREATE USER MAPPING FOR postgres SERVER historize_foreign_cron OPTIONS (user 'postgres', password 'password')"
      - run: pg_prove -v -r --ext .sql test/
